import Vue from 'vue'
import { Icon, Button, CellGroup, Cell, Tabbar, TabbarItem, Field, Dialog, NavBar, Toast, Search, Tabs, Tab, DatetimePicker, Popup, DropdownMenu, DropdownItem, Tag, CheckboxGroup, Checkbox, IndexBar, IndexAnchor, Uploader, Overlay, Collapse, CollapseItem, Swipe, SwipeItem, Notify, RadioGroup, Radio, Loading,Sticky} from 'vant'

Vue.use(Icon)
Vue.use(Button)
Vue.use(CellGroup)
Vue.use(Cell)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Field)
Vue.use(Dialog)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(DatetimePicker)
Vue.use(Popup)
Vue.use(DropdownMenu).use(DropdownItem)
Vue.use(Tag)
Vue.use(Checkbox).use(CheckboxGroup)
Vue.use(IndexBar).use(IndexAnchor)
Vue.use(Uploader)
Vue.use(Overlay)
Vue.use(Collapse).use(CollapseItem)
Vue.use(Swipe).use(SwipeItem)
Vue.use(Notify)
Vue.use(RadioGroup).use(Radio)
Vue.use(Loading)
Vue.use(Sticky)
